[package]
name = "calibre-merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = { version = "0.10", default-features = false, features = ["std"] }
sp-std = { workspace = true, default-features = false }

[features]
default = ["std"]
std = ["blake2/std", "sp-std/std"]

[dev-dependencies]
sp-core = { workspace = true, features = ["std"] }
